ccflags-y += -I$(src)/../mt7697common/
ccflags-y += -I$(src)/../mt7697q-driver/
ccflags-y += -I$(src)/../mt7697serial-driver/

mt7697core-y    += main.o ioctl.o cfg80211.o wmi.o txrx.o

obj-m    += mt7697core.o
